### ISSUE TITLE
exporting multiple sheets in one excel 

### ISSUE THREAD

**Issue by Deepaktogarla** [Moblox/mongo-xlsx#21]
iam trying this to generate multiple sheets in one excel,but iam getting output as object

const sheets = ['a','b'];
mongoData2XlsxMultiPage(monogData, sheets, options, callback)

**Comment by user1702** [comment]
@Deepaktogarla Can you help me in converting below data into multiple sheet in one excel..

`[[{"name":"John","address":[{"street":"HongKong"}]},{"name":"Mike","address":[{"street":"China"}]}],[{"name":"John","address":[{"street":"HongKong"}]},{"name":"Mike","address":[{"street":"China"}]}]]`

**Comment by Deepaktogarla** [comment]
i tried to solve it ,but i was unsuccessful.  I used two different excel files instead of multiple sheets in one excel
