### ISSUE TITLE
can not assign save flag to false

### ISSUE THREAD

**Issue by anhvietcx** [Moblox/mongo-xlsx#26]
I try to assign save flag to false but unsuccess, I have investigated and found that below code make stuck
`if (!options.save)      {options.save      = makeDefault('save');}` 
option.save always set to true.

Please take time to fix this bug.
Thanks

**Comment by anhvietcx** [comment]
I have found pull requested fix this bug. But I install from npm so the bug still exists.
Thanks.

**Comment by yuercl** [comment]
need publish new version to npmjs repo
