### ISSUE TITLE
Adding styles

### ISSUE THREAD

**Issue by ashish-agarwal24** [Moblox/mongo-xlsx#7]
Can someone give a snippet on how to add styles ?

**Comment by acedward** [comment]
No simple answer. 
The converter uses: https://github.com/mgcrea/node-xlsx that is wrapper for https://github.com/SheetJS/js-xlsx 


js-xlsx provides many styling mechanism, perhaps it is easier to apply the style after the xlsx is generated.

**Comment by ashish-agarwal24** [comment]
so after generating xlsx file , i need to loop through the cells and apply the styles?

**Comment by acedward** [comment]
It is possible to modify the `node-xlsx` library to set the cell formatting style (e.g, date format, amount of decimal numbers) but it is quite complicated. 

I think the best option is using js-xlsx after the xlsx is generated 😞 As you say loop though the columns/rows and apply the style.

We are planning to rewrite the converter to no longer use `node-xlsx` and use directly `js-xlsx` so we can do this (we are facing the same problem)

**Comment by ashish-agarwal24** [comment]
Ok... Thanks for the help.. :)
